src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 20)]
    private $designation;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: PFE::class)]
    private $pfeCollection;

    public function __construct()
    {
        $this->pfeCollection = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    /**
     * @return Collection<int, PFE>
     */
    public function getPfeCollection(): Collection
    {
        return $this->pfeCollection;
    }

    public function addPfeCollection(PFE $pfeCollection): self
    {
        if (!$this->pfeCollection->contains($pfeCollection)) {
            $this->pfeCollection[] = $pfeCollection;
            $pfeCollection->setEntreprise($this);
        }

        return $this;
    }

    public function removePfeCollection(PFE $pfeCollection): self
    {
        if ($this->pfeCollection->removeElement($pfeCollection)) {
            // set the owning side to null (unless already changed)
            if ($pfeCollection->getEntreprise() === $this) {
                $pfeCollection->setEntreprise(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->getDesignation();
    }
}

src/Entity/PFE.php
<?php

namespace App\Entity;

use App\Repository\PFERepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PFERepository::class)]
class PFE
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 20)]
    private $titre;

    #[ORM\Column(type: 'string', length: 20)]
    private $nom_etudiant;

    #[ORM\ManyToOne(targetEntity: Entreprise::class, inversedBy: 'entreprise')]
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNomEtudiant(): ?string
    {
        return $this->nom_etudiant;
    }

    public function setNomEtudiant(string $nom_etudiant): self
    {
        $this->nom_etudiant = $nom_etudiant;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
    public function __toString(): string
    {
        return $this->getTitre()." ".$this->getNomEtudiant();
    }
}

src/Form/PFEType.php
<?php

namespace App\Form;

use App\Entity\PFE;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PFEType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('nom_etudiant')
            ->add('entreprise')
            ->add("Submit",SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PFE::class,
        ]);
    }
}

src/Controller/PFEController.php
<?php

namespace App\Controller;

use App\Entity\PFE;
use App\Form\PFEType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route('/pfe')]
class PFEController extends AbstractController
{
    private $manager;
    public function __construct(ManagerRegistry $doctrine)
    {
        $this->manager = $doctrine->getManager();
    }
    #[Route('/ajout', name: 'add_pfe')]
    public function ajout(Request $request): Response
    {
        $pfe = new PFE();
        $form= $this->createForm (PFEType::class,$pfe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
                $this->manager->persist($pfe);
                $this->manager->flush();
                $this->addFlash("success","The pfe ".$pfe." is successfully added" );
                return $this->redirectToRoute('pfe',["id"=>$pfe->getId()]);}
        return $this->render('pfe/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('/list',name: "list_pfes")]
    public function list(): Response
    {
        $this->addFlash("success","Nombre de Pfe par entreprise" );
        $result = $this->manager->getRepository("App\Entity\Entreprise")->findAll();
        return $this->render('pfe/list.html.twig', [
            'entreprises' => $result,
        ]);
    }
    #[Route('/{id}',name: "pfe")]
    public function pfe(PFE $pfe): Response
    {

        return $this->render('pfe/pfe.html.twig', [
            'pfe' => $pfe,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="{{ asset('node_modules/bootstrap/dist/css/bootstrap.css') }}">
    <title>{% block title %} Gl2 G2 {% endblock %}</title>
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{{path('list_pfes')}}">Entreprises</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="index.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Layouts
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="layout-static.html">Static Navigation</a>
                            <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Pages
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                Authentication
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="login.html">Login</a>
                                    <a class="nav-link" href="register.html">Register</a>
                                    <a class="nav-link" href="password.html">Forgot Password</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                Error
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="401.html">401 Page</a>
                                    <a class="nav-link" href="404.html">404 Page</a>
                                    <a class="nav-link" href="500.html">500 Page</a>
                                </nav>
                            </div>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                Start Bootstrap
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <div class="container">
            <main>
                {% for flashMessage in app.session.flashbag.get('error') %}
                    <div class="alert alert-danger">
                        {{ flashMessage }}
                    </div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('success') %}
                    <div class="alert alert-success">
                        {{ flashMessage }}
                    </div>
                {% endfor %}
                {% for flashMessage in app.session.flashbag.get('info') %}
                    <div class="alert alert-info">
                        {{ flashMessage }}
                    </div>
                {% endfor %}
                {% block body %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('js/scripts.js') }}"></script>
</body>
</html>

templates/pfe/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{form(form)}}

{% endblock %}

{% block title %}

{% endblock %}

templates/pfe/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    <style>
        #c {
            margin: 0.2%;
        }
    </style>
    <div class="container row">
        {% for entreprise in entreprises %}
            {% if loop.index%2 ==0%}
            <div class="card w-25 col-auto text-white" id="c" style="background-color: #f8d7da">
                <div class="card-body">
                    <h5 class="card-title">{{ entreprise.designation }}</h5>
                    <p class="card-text">{{entreprise.pfeCollection|length}} PFE(s)</p>
                </div>
            </div>
            {%else%}
                <div class="card w-25 col-auto text-black" id="c" style="background-color:#dfc2c4 ">
                    <div class="card-body">
                        <h5 class="card-title">{{ entreprise.designation }}</h5>
                        <p class="card-text">{{entreprise.pfeCollection|length}} PFE(s)</p>
                    </div>
                </div>
            {%endif%}
        {% endfor %}
    </div>
    <br>
    <a href="{{path('add_pfe')}}" class="btn btn-dark">Add PFE</a>

{% endblock %}

templates/pfe/pfe.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    <style>
        #nada {
            margin-left : 30%;
            margin-top : 7%;
            background-color: #f8d7da;
        }
    </style>
    <div class="card" style="width: 25rem;" id="nada">
        <div class="card-body">
            <h5 class="card-title">titre : {{pfe.titre}}</h5>
            <br>
            <p class="card-text">nom étudiant : {{pfe.nomEtudiant}}</p>
            <p class="card-text">ENTREPRISE : {{pfe.entreprise}}</p>
            <a href="{{ path('list_pfes') }}" class="btn  btn-light" >liste des entreprises</a>
        </div>
    </div>
{% endblock %}